In [2]:
import numpy as np

In [5]:
x = np.array([[0., 1.],
              [2., 3.],
              [4., 5.]])

In [8]:
x.reshape(6, 1)

array([[0.],
       [1.],
       [2.],
       [3.],
       [4.],
       [5.]])

In [11]:
x.reshape(2, 3)

array([[0., 1., 2.],
       [3., 4., 5.]])

In [12]:
x.reshape(3, 2)

array([[0., 1.],
       [2., 3.],
       [4., 5.]])